as yet unclassified
lineAsKnowledgeEntry: line
	"Given a line, does it parse like book / article information? If so return a RuxbinKnowledgeEntry for later population. If not, return nil"
	"scope: class-variables  &  instance-variables"	
			
	||
	
		  "for declaration lines we have about two options:
		
		   Setting up Multi-cluster Ingress  |  Kubernetes Engine Documentation  |  Google Cloud. [web]. Retrieved from:  https://cloud.google.com/kubernetes-engine/docs/how-to/multi-cluster-ingress-setup
		  and 
		
		  author. Book name. [Kindle ebok] (loc 12345)"
